# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_crawler_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledurl',
            name='alive',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
